(() => {
'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s), screens=[...document.querySelectorAll('.screen')];
const ui={hud:$('#hud'),score:$('#score'),best:$('#best'),coins:$('#coins'),lives:$('#lives'),distance:$('#distance'),power:$('#power-status')};
let W=0,H=0,dpr=1,ground=0,state='menu',last=0,worldTime=0,audio=null,sound=localStorage.getItem('neonSound')!=='off';
let player,obstacles,coinList,powerups,particles,score,distance,coins,lives,speed,spawnTimer,coinTimer,powerTimer,invincible,activePower,shake,flash;
const best=()=>Number(localStorage.getItem('neonRunnerBest')||0);

function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ground=Math.floor(H*.78);if(player&&!player.jumping)player.y=ground-player.h;}
addEventListener('resize',resize);resize();
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));}
function reset(){score=0;distance=0;coins=0;lives=3;speed=430;spawnTimer=1.4;coinTimer=.8;powerTimer=10;invincible=0;activePower=null;shake=flash=0;obstacles=[];coinList=[];powerups=[];particles=[];player={x:Math.max(60,W*.14),y:ground-62,w:45,h:62,vy:0,jumping:false,anim:0};updateHud();}
function start(){initAudio();reset();state='playing';show('');ui.hud.classList.remove('hidden');last=performance.now();}
function menu(){state='menu';show('start-screen');ui.hud.classList.add('hidden');}
function pause(){if(state!=='playing')return;state='paused';show('pause-screen');}
function resume(){state='playing';show('');last=performance.now();}
function jump(){if(state!=='playing'||player.jumping)return;player.vy=-Math.min(820,H*1.15);player.jumping=true;burst(player.x+20,player.y+player.h,'#27f3ff',6);sfx('jump');}
function initAudio(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();}
function sfx(type){if(!sound||!audio)return;const map={jump:[270,.1,'square'],coin:[880,.08,'sine'],power:[440,.25,'sine'],hurt:[95,.25,'sawtooth'],over:[55,.6,'sawtooth']},v=map[type];const o=audio.createOscillator(),g=audio.createGain();o.type=v[2];o.frequency.setValueAtTime(v[0],audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(30,v[0]*(type==='power'?2:.55)),audio.currentTime+v[1]);g.gain.setValueAtTime(.08,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+v[1]);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+v[1]);}
function toggleSound(){sound=!sound;localStorage.setItem('neonSound',sound?'on':'off');$('#sound-btn').textContent=sound?'♪':'×';initAudio();}
function burst(x,y,color,n=12){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*260,vy:(Math.random()-.8)*240,life:.5+Math.random()*.4,color,size:2+Math.random()*4});}
function obstacle(){const difficulty=Math.min(1,score/12000),types=['box','barrier','spike'];if(score>2500)types.push('drone');const type=types[Math.floor(Math.random()*types.length)];let o={type,x:W+50,y:ground,w:45,h:45,phase:Math.random()*6};if(type==='barrier'){o.w=26;o.h=68}else if(type==='spike'){o.w=55;o.h=31}else if(type==='drone'){o.w=52;o.h=30;o.y=ground-70-Math.random()*45}else o.h=40+Math.random()*25;o.y-=o.h;obstacles.push(o);if(difficulty>.55&&Math.random()<.25)obstacles.push({...o,x:o.x+100+(Math.random()*30),h:type==='spike'?31:38,y:type==='drone'?ground-35:ground-(type==='spike'?31:38)});}
function coinWave(){const n=3+Math.floor(Math.random()*4),arc=Math.random()<.65;for(let i=0;i<n;i++)coinList.push({x:W+50+i*48,y:ground-45-(arc?Math.sin(i/(n-1)*Math.PI)*75:Math.random()*20),r:10,spin:Math.random()*6});}
function powerSpawn(){const types=['shield','magnet','double','boost'];powerups.push({type:types[Math.floor(Math.random()*4)],x:W+60,y:ground-75-Math.random()*80,r:17,spin:0});}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y+a.h>b.y&&a.y<b.y+b.h;}
function hitbox(o){return o.r?{x:o.x-o.r,y:o.y-o.r,w:o.r*2,h:o.r*2}:o;}
function damage(o){if(invincible>0)return;if(activePower?.type==='shield'){activePower=null;invincible=1;burst(o.x,o.y,'#27f3ff',22);sfx('power');return;}lives--;invincible=1.5;shake=.3;flash=.18;burst(player.x+20,player.y+25,'#ff2bd6',20);sfx('hurt');if(lives<=0)gameOver();}
function getPower(p){activePower={type:p.type,time:p.type==='shield'?999:8};if(p.type==='boost'){activePower.time=5;score+=500}burst(p.x,p.y,'#a855ff',25);sfx('power');}
function update(dt){worldTime+=dt;const multiplier=activePower?.type==='double'?2:1,boost=activePower?.type==='boost'?1.28:1;score+=dt*55*multiplier;distance+=dt*speed/18;speed=Math.min(780,430+score/38);invincible=Math.max(0,invincible-dt);shake=Math.max(0,shake-dt);flash=Math.max(0,flash-dt);if(activePower&&activePower.type!=='shield'){activePower.time-=dt;if(activePower.time<=0)activePower=null}
 player.vy+=2100*dt;player.y+=player.vy*dt;if(player.y>=ground-player.h){player.y=ground-player.h;player.vy=0;player.jumping=false}player.anim+=dt*(speed/55);
 spawnTimer-=dt;if(spawnTimer<=0){obstacle();spawnTimer=Math.max(.68,1.55-score/17000)+Math.random()*.55}
 coinTimer-=dt;if(coinTimer<=0){coinWave();coinTimer=2.4+Math.random()*2.1}
 powerTimer-=dt;if(powerTimer<=0){powerSpawn();powerTimer=10+Math.random()*8}
 const scroll=speed*boost*dt;obstacles.forEach(o=>{o.x-=scroll;if(o.type==='drone')o.y+=Math.sin(worldTime*4+o.phase)*.5});coinList.forEach(c=>{c.x-=scroll;c.spin+=dt*8;if(activePower?.type==='magnet'){const dx=player.x+20-c.x,dy=player.y+25-c.y,d=Math.hypot(dx,dy);if(d<220){c.x+=dx*dt*5;c.y+=dy*dt*5}}});powerups.forEach(p=>{p.x-=scroll;p.spin+=dt*3});
 const ph={x:player.x+7,y:player.y+6,w:player.w-14,h:player.h-7};obstacles.forEach(o=>{if(!o.hit&&overlap(hitbox(o),ph)){o.hit=true;damage(o)}});coinList.forEach(c=>{if(!c.got&&overlap(hitbox(c),ph)){c.got=true;coins++;score+=100*multiplier;burst(c.x,c.y,'#ffe03d');sfx('coin')}});powerups.forEach(p=>{if(!p.got&&overlap(hitbox(p),ph)){p.got=true;getPower(p)}});
 obstacles=obstacles.filter(o=>o.x>-140);coinList=coinList.filter(c=>!c.got&&c.x>-40);powerups=powerups.filter(p=>!p.got&&p.x>-50);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=500*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);updateHud();}
function updateHud(){ui.score.textContent=String(Math.floor(score)).padStart(6,'0');ui.best.textContent=String(Math.max(best(),Math.floor(score))).padStart(6,'0');ui.coins.textContent=coins;ui.lives.textContent='♥ '.repeat(lives).trim()||'—';ui.distance.textContent=Math.floor(distance)+' m';if(activePower){const names={shield:'SHIELD READY',magnet:'COIN MAGNET',double:'DOUBLE SCORE',boost:'SPEED BOOST'};ui.power.textContent=names[activePower.type]+(activePower.time<100?'  '+Math.ceil(activePower.time)+'s':'');ui.power.classList.remove('hidden')}else ui.power.classList.add('hidden');}
function gameOver(){state='over';const final=Math.floor(score),newBest=Math.max(best(),final);localStorage.setItem('neonRunnerBest',newBest);$('#final-score').textContent=final;$('#final-best').textContent=newBest;$('#final-coins').textContent=coins;$('#final-distance').textContent=Math.floor(distance)+' m';show('gameover-screen');sfx('over');}

function neonLine(x1,y1,x2,y2,color,width=2){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.shadowColor=color;ctx.shadowBlur=10;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.shadowBlur=0;}
function background(){const t=worldTime,s=state==='playing'?speed:80;ctx.fillStyle='#07051b';ctx.fillRect(0,0,W,H);const grad=ctx.createRadialGradient(W*.55,H*.55,20,W*.55,H*.55,W*.7);grad.addColorStop(0,'#231050');grad.addColorStop(.5,'#090823');grad.addColorStop(1,'#03020e');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);
 for(let layer=0;layer<2;layer++){const bw=65+layer*35,off=-(t*s*(.025+layer*.035))%(bw+8),base=ground-(95+layer*55);for(let x=off-100;x<W+100;x+=bw+8){const seed=Math.abs(Math.sin((x-off+layer*99)*.13)),h=45+seed*(100+layer*75);ctx.fillStyle=layer?'#100c35':'#0a0825';ctx.fillRect(x,base-h,bw,h);for(let wy=base-h+14;wy<base-8;wy+=18)for(let wx=x+10;wx<x+bw-5;wx+=18){if(Math.sin(wx*8+wy)>-.3){ctx.fillStyle=(Math.floor(wx+wy)%3)?'#1b5270':'#6c185e';ctx.globalAlpha=.45;ctx.fillRect(wx,wy,5,7);ctx.globalAlpha=1}}}}
 ctx.fillStyle='#0a0825';ctx.fillRect(0,ground,W,H-ground);neonLine(0,ground,W,ground,'#27f3ff',3);for(let i=0;i<16;i++){const x=((i*130-t*s*.55)%(W+260)+W+260)%(W+260)-130;neonLine(x,ground+30,x-45,ground+H*.2,'#6b197d',1)}for(let y=ground+28;y<H;y+=32)neonLine(0,y,W,y,'#19124a',1);
 for(let i=0;i<4;i++){const x=((i*390-t*s*.12)%(W+450)+W+450)%(W+450)-100,y=ground-160-(i%2)*70;ctx.fillStyle='#10103c';ctx.fillRect(x,y,90,34);ctx.strokeStyle=i%2?'#ff2bd6':'#27f3ff';ctx.strokeRect(x,y,90,34);ctx.fillStyle=ctx.strokeStyle;ctx.font='700 10px Oxanium';ctx.textAlign='center';ctx.fillText(i%2?'NOVA // 24':'NEON DISTRICT',x+45,y+21)}}
function drawPlayer(){const p=player,blink=invincible>0&&Math.floor(invincible*12)%2===0;if(blink)return;ctx.save();ctx.translate(p.x,p.y);if(shake)ctx.translate((Math.random()-.5)*10,(Math.random()-.5)*6);if(player.jumping)ctx.rotate(Math.sin(worldTime*7)*.08);const leg=Math.sin(p.anim)*8;ctx.shadowColor=activePower?'#a855ff':'#27f3ff';ctx.shadowBlur=16;ctx.strokeStyle='#27f3ff';ctx.lineWidth=6;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(17,45);ctx.lineTo(13+leg,58);ctx.moveTo(29,45);ctx.lineTo(34-leg,58);ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#191543';ctx.beginPath();ctx.roundRect(8,14,32,37,10);ctx.fill();ctx.strokeStyle='#8d56ff';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#f1f4ff';ctx.beginPath();ctx.roundRect(5,0,38,29,12);ctx.fill();ctx.fillStyle='#151334';ctx.beginPath();ctx.roundRect(10,7,28,13,6);ctx.fill();ctx.fillStyle='#27f3ff';ctx.shadowColor='#27f3ff';ctx.shadowBlur=9;ctx.fillRect(16,11,6,4);ctx.fillRect(27,11,6,4);ctx.shadowBlur=0;ctx.fillStyle='#ff2bd6';ctx.fillRect(39,24,6,13);ctx.restore();}
function drawObjects(){obstacles.forEach(o=>{ctx.save();ctx.translate(o.x,o.y);ctx.shadowColor='#ff2bd6';ctx.shadowBlur=12;ctx.strokeStyle='#ff2bd6';ctx.lineWidth=2;ctx.fillStyle='#17102f';if(o.type==='spike'){ctx.beginPath();ctx.moveTo(0,o.h);for(let x=0;x<o.w;x+=18){ctx.lineTo(x+9,0);ctx.lineTo(x+18,o.h)}ctx.fill();ctx.stroke()}else if(o.type==='drone'){ctx.beginPath();ctx.roundRect(0,0,o.w,o.h,12);ctx.fill();ctx.stroke();neonLine(10,o.h/2,o.w-10,o.h/2,'#ffe03d')}else{ctx.fillRect(0,0,o.w,o.h);ctx.strokeRect(0,0,o.w,o.h);neonLine(5,5,o.w-5,o.h-5,'#722765');neonLine(o.w-5,5,5,o.h-5,'#722765')}ctx.restore()});
 coinList.forEach(c=>{ctx.save();ctx.translate(c.x,c.y);ctx.scale(Math.max(.2,Math.abs(Math.cos(c.spin))),1);ctx.fillStyle='#ffe03d';ctx.shadowColor='#ffe03d';ctx.shadowBlur=16;ctx.beginPath();ctx.arc(0,0,c.r,0,7);ctx.fill();ctx.fillStyle='#ff9f1c';ctx.beginPath();ctx.arc(0,0,4,0,7);ctx.fill();ctx.restore()});
 const icons={shield:'S',magnet:'M',double:'2×',boost:'»'};powerups.forEach(p=>{ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.spin);ctx.fillStyle='#251050';ctx.strokeStyle='#a855ff';ctx.lineWidth=3;ctx.shadowColor='#a855ff';ctx.shadowBlur=18;ctx.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3;ctx.lineTo(Math.cos(a)*p.r,Math.sin(a)*p.r)}ctx.closePath();ctx.fill();ctx.stroke();ctx.rotate(-p.spin);ctx.fillStyle='#fff';ctx.font='700 11px Oxanium';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(icons[p.type],0,1);ctx.restore()});
 particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life*1.5);ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=8;ctx.fillRect(p.x,p.y,p.size,p.size)});ctx.globalAlpha=1;}
function render(){background();if(player){drawObjects();drawPlayer()}if(flash){ctx.fillStyle=`rgba(255,43,214,${flash})`;ctx.fillRect(0,0,W,H)}}
function loop(now){const dt=Math.min(.033,(now-last)/1000||0);last=now;if(state==='playing')update(dt);else worldTime+=dt*.35;render();requestAnimationFrame(loop)}requestAnimationFrame(loop);

$('#play-btn').onclick=$('#how-play-btn').onclick=$('#again-btn').onclick=start;$('#how-btn').onclick=()=>show('how-screen');$('#back-btn').onclick=menu;$('#pause-btn').onclick=pause;$('#resume-btn').onclick=resume;$('#restart-btn').onclick=start;$('#menu-btn').onclick=$('#over-menu-btn').onclick=menu;$('#sound-btn').onclick=toggleSound;$('#sound-btn').textContent=sound?'♪':'×';
addEventListener('keydown',e=>{if(['Space','ArrowUp'].includes(e.code)){e.preventDefault();jump()}if(e.code==='Escape'||e.code==='KeyP'){state==='playing'?pause():state==='paused'&&resume()}});
canvas.addEventListener('pointerdown',e=>{e.preventDefault();jump()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause()});
})();
